- name: Configure Webservers to serve a static webpage with an S3 image
  hosts: all
  become: yes
  tasks:

    - name: Check connectivity to each host
      ping:
      ignore_errors: yes

    - name: Ensure Apache (httpd) is installed
      yum:
        name: httpd
        state: present

    - name: Ensure Apache is running and enabled
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Download bliss.jpeg from S3 using get_url
      get_url:
        url: "https://acs-730-final-project.s3.us-east-1.amazonaws.com/clock.png"
        dest: /var/www/html/bliss.jpeg
        mode: "0644"
      # This task fetches the image from S3 (which must be publicly accessible)

    - name: Create or update index.html to reference the downloaded image
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
            <head>
              <title>Webserver</title>
            </head>
            <body>
              <h1>Hello from {{ inventory_hostname }}</h1>
              <img src="bliss.jpeg" alt="Bliss Image" />
            </body>
          </html>
      notify:
        - Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: httpd
        state: restarted
