
name: Terraform CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      # These environment variables will be picked up by any AWS CLI or SDK calls.
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: us-east-1
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Determine Environment
        id: getenv
        run: |
          if [[ "$GITHUB_REF" == refs/heads/* ]]; then
            branch="${GITHUB_REF#refs/heads/}"
            case $branch in
              main) env="prod" ;;
              release/*) env="staging" ;;
              *) env="dev" ;;
            esac
          else
            env="dev" # Default for tags/other triggers
          fi
          echo "environment=$env" >> $GITHUB_OUTPUT
          echo "branch=$branch" >> $GITHUB_OUTPUT

      - name: Install TFLint
        run: |
          curl -sSLO https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh
          chmod +x install_linux.sh
          sudo ./install_linux.sh

      - name: Terraform Init, Validate & Plan
        run: |
          ENV_DIR="terraform/${{ steps.getenv.outputs.environment }}"
          echo "Using environment directory: $ENV_DIR"
          
          # Force AWS CLI to use us-east-1
          export AWS_REGION=us-east-1
          export AWS_DEFAULT_REGION=us-east-1
          
          # Initialize with explicit endpoint configuration
          terraform -chdir="$ENV_DIR" init \
            -backend-config="bucket=ac5730-final-project-bucket" \
            -backend-config="key=${{ steps.getenv.outputs.environment }}/terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="endpoint=https://s3.us-east-1.amazonaws.com" \
            -backend-config="skip_region_validation=true" \
            -reconfigure
          
          # Validate and plan
          terraform -chdir="$ENV_DIR" validate
          terraform -chdir="$ENV_DIR" plan -input=false

  ansible:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      # If you need AWS credentials as well, ensure they’re set as secrets.
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Python Dependencies and Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible boto3 botocore

      - name: Setup SSH Private Key
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa

      - name: Verify Installed Versions
        run: |
          ansible --version
          python --version
          pip --version

      - name: Test Dynamic Inventory Parsing
        run: |
          # This lists the inventory generated by the aws_ec2 plugin.
          ansible-inventory --list -i ansible/aws_ec2.yaml
        continue-on-error: true

      - name: Run Ansible Playbook
        run: |
          cd ansible
          # Ensure that your dynamic inventory file (aws_ec2.yaml) is in the same ansible folder.
          ansible-playbook -i aws_ec2.yaml webserver-setup.yml --private-key $HOME/.ssh/id_rsa -u ec2-user || true
