name: Terraform CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Explicit version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}  # Only if using temp credentials
          aws-region: us-east-1

      - name: Terraform Init
        run: |
          cd "${{ github.event.inputs.environment || 'default' }}"  # Fallback directory
          terraform init

      - name: Terraform Validate
        run: |
          cd "${{ github.event.inputs.environment || 'default' }}"
          terraform validate

      - name: Terraform Plan
        run: |
          cd "${{ github.event.inputs.environment || 'default' }}"
          terraform plan -input=false

  ansible:
    runs-on: ubuntu-latest
    needs: [terraform]  # Wait for Terraform first
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python/Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install ansible boto3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts  # For GitHub if needed

      - name: Run Ansible Playbook
        run: |
          cd ansible
          ansible-playbook -i aws_ec2.yaml webserver-setup.yml \
            --private-key ~/.ssh/id_rsa \
            -u ec2-user